apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    name: erynis-monitoring
  name: erynis-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
