---
- name: "Pull index image '{{ oil_index_image }}'"
  shell: "{{ container_tool }} pull {{ oil_index_image }}"

- name: "Set time to 'oil_temp'"
  set_fact:
    oil_temp: "ignore_list"
    ignore_list: []

- name: "Create the {{ oil_temp }} container"
  shell: "{{ container_tool }} rm -f {{ oil_temp }}"

- name: "Create the {{ oil_temp }} container"
  shell: "{{ container_tool }} create --name {{ oil_temp }} {{ oil_index_image }}"

- name: "Cp ignore list"
  shell: "{{ container_tool }} cp {{ oil_temp }}:/{{ oil_ignore_list_file }} {{ oil_dir }}"
  failed_when: false

- name: "Check for file '{{ oil_dir }}/{{ oil_ignore_list_file }}'"
  stat:
    path: "{{ oil_dir }}/{{ oil_ignore_list_file }}"
  register: oil_ignore_list_presence

- name: "Getting content file '{{ oil_dir }}/{{ oil_ignore_list_file }}'"
  shell: cat "{{ oil_dir }}/{{ oil_ignore_list_file }}"
  register: oil_ignore_list_data
  when: oil_ignore_list_presence.stat.exists

- name: "Building 'ignore_list'"
  set_fact:
    ignore_list: "{{ oil_ignore_list_data.stdout | from_yaml }}"
  when: oil_ignore_list_data.stdout is defined

- name: "Print 'ignore_list'"
  debug:
    var: ignore_list
# - debug:
#     var: oil_temp
