---
- name: "Ensure that the {{ oil_dir }} directory exists"
  file:
    state: directory
    path: "{{ oil_dir }}"

- name: "Ensure that the file '{{ oil_dir }}/{{ oil_ignore_list_file }}' doen't exist"
  file:
    state: "absent"
    path: "{{ oil_dir }}/{{ oil_ignore_list_file }}"

# - name: "Check if {{ oil_dir }}/{{ oil_ignore_list_file }} exists"
#   stat:
#     path: "{{ oil_dir }}/{{ oil_ignore_list_file }}"
#   register: oil_ignore_list_presence

- name: "Load ignore list"
  include_tasks: "load.yml"
  when:
    - oil_load|bool
    - oil_index_image is defined
    - oil_index_image|length>0



# - name: "Check for file '{{ oil_dir }}/{{ oil_ignore_list_file }}'"
#   stat:
#     path: "{{ oil_dir }}/{{ oil_ignore_list_file }}"
#   register: ignore_list_add_file_st

# - name: "Getting content file '{{ oil_dir }}/{{ oil_ignore_list_file }}'"
#   shell: cat "{{ oil_dir }}/{{ oil_ignore_list_file }}"
#   register: oil_ignore_list_data
#   when: ignore_list_add_file_st.stat.exists
# - name: "Add 'ignore_list_from_file' to 'ignore_list'"
#   set_fact:
#     ignore_list: "{{ ignore_list | union(ignore_list_from_file) }}"
#   when: ignore_list_add_file is defined

- name: "Push ignore list to the index"
  include_tasks: "push.yml"
  when:
    - oil_push|bool
    - oil_index_image is defined
    - oil_index_image|length>0
