---
- name: "Save ignore_list variable to a file"
  copy:
    content: "{{ ignore_list }}"
    dest: "{{ oil_ignore_list_file_path }}"
  when:
   - ignore_list is defined
   - ignore_list|length > 0

- name: "Check if {{ oil_ignore_list_file_path }} exists"
  stat:
    path: "{{ oil_ignore_list_file_path }}"
  register: oil_ignore_list_presence

- name: "Build and push"
  block:
    - name: "Copy Dockerfile"
      template:
        src: "Dockerfile"
        dest: "{{ oil_dockerfile }}"

    - name: "Build index image '{{ oil_index_image }}'"
      shell: "{{ container_tool }} build --no-cache -t {{ oil_index_image }} {{ oil_dir }}"

    - name: "Push index image '{{ oil_index_image }}'"
      shell: "{{ container_tool }} push {{ oil_index_image }}"
  when:
    - oil_ignore_list_presence.stat.exists == true