name: "Build and test upstream CI image"

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      # Fixes https://github.com/actions/virtual-environments/issues/3080
      STORAGE_OPTS: overlay.mount_program=/usr/bin/fuse-overlayfs
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: "Build the upstream_ci_image inside Dockerfiles"
        run: |
          podman --version
          podman build -t upstream_ci_image:latest -f Dockerfiles/ci/Dockerfile

      - name: "Run the unit tests for the upstream operator CI"
        continue-on-error: false
        run: |
          podman run -it -v $PWD:/project/operator-test-playbooks -v ./Dockerfiles/ci:/project/test_dir -e TEST_DIR=/project/test_dir upstream_ci_image:latest